blank_issues_enabled: false
contact_links:
  - name: Remote Zoom Meetup Registration
    url: https://airtable.com/shrsSH1on1BjbjTNi
    about: If you would like to host a remote meetup you can register for a free Zoom meeting session on Airtable!
